language: python

# Specifica le versioni di Python (per i test Django)
python:
  - "3.12"

#services:
#  - postgresql  # Se usi PostgreSQL per il database Django

# Imposta variabili d'ambiente
env:
  - DJANGO_SETTINGS_MODULE=bookinghub.settings
#  - DATABASE_URL=postgres://postgres@localhost/test_db  # Connessione al database di test

# Installa dipendenze necessarie prima di eseguire i test
before_install:
  - pip install -r requirements.txt  # Installa le dipendenze di Django
  - nvm install node  # Installa Node.js tramite nvm (Node Version Manager)
  - node -v  # Verifica la versione di Node.js
  - npm install -g npm@latest  # Aggiorna npm all'ultima versione
  - cd hotel-booking-frontend  # Vai nella cartella del frontend React
  - npm install  # Installa le dipendenze del frontend
  - cd ..  # Torna alla cartella principale

# Configura e prepara il database prima dei test Django
before_script:
  # - psql -c 'create database test_db;' -U postgres  # Crea il database di test
  - python manage.py migrate  # Applica le migrazioni di Django

# Esegui i test Python e npm
script:
  - python manage.py test  # Esegui i test Django
  - cd frontend && npm test -- --watchAll=false  # Esegui i test React