version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bookinghub_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - bookinghub_postgres_data:/var/lib/postgresql/data

volumes:
  bookinghub_postgres_data:
