# Generated by Django 5.1.4 on 2025-01-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("verifica", "Verifica"),
                    ("approvata", "Approvata"),
                    ("rigettata", "Rigettata"),
                ],
                default="verifica",
                max_length=10,
            ),
        ),
    ]
