# Generated by Django 5.1.2 on 2024-10-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelService',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
