name: Run Tests

on:
  push:
    branches:
      - main  # Esegui i test sui push al branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: bookinghub.settings  # Configura le variabili d'ambiente di Django

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run Django tests
        run: pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: |
          cd hotel-booking-frontend
          npm install

      - name: Run React tests
        run: |
          cd hotel-booking-frontend
          npm test -- --watchAll=false
